baseurl = "https://blog.toddmeinershagen.com/"
title = "Todd's Thoughts"
author = "Todd Meinershagen"
copyright = "&copy; 2017. All rights reserved."
canonifyurls = true
paginate = 10
theme = "blackburn"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Random access to my thoughts, ideas, and experiences…"
  brand = "MENU"
  googleAnalytics = "UA28028155"
  disqus = "blog-toddmeinershagen-com"
  highlightjs = "androidstudio"
  highlightjs_extra_languages = ["yaml"]
  dateFormat = "Monday, January 02, 2006"
  custom_css = ["css/my.css"]
  custom_js = ["js/my.js"]
  favicon = "https://www.qualitysoftwarematters.com/wp-content/uploads/2015/06/Quality-Software-Matters-Logo-16x161.ico"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
 #[[menu.main]]
 #   name = "Posts"
 #   pre = "<i class='fa fa-list fa-fw'></i>"
 #   weight = 2
 #   identifier = "post"
 #   url = "/"

  #[[menu.main]]
  #  name = "Technical"
  #  pre = "<i class='fa fa-folder fa-fw'></i>"
  #  weight = 3
  #  identifier = "technical"
  #  url = "/topics/technical"
  #[[menu.main]]
  #  name = "Christian"
  #  pre = "<i class='fa fa-folder fa-fw'></i>"
  #  weight = 4
  #  identifier = "christian"
  #  url = "/topics/christian"

  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 5
    identifier = "about"
    url = "/about/"
  #[[menu.main]]
  #  name = "Contact"
  #  pre = "<i class='fa fa-phone fa-fw'></i>"
  #  weight = 6
  #  url = "https://github.com/toddmeinershagen/feedback/issues/new"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # SNS microblogging
  twitter = "tmeinershagen"
  # gnusocial = "*" # Specify href (e.g. https://quitter.se/yourusername)
  # facebook = "*"
  googleplus = "ToddMeinershagen"
  # weibo = "*"
  tumblr = "toddmeinershagen"

  # SNS photo/video sharing
  # instagram = "*"
  # flickr = "*"
  # photo500px = "*"
  # pinterest = "*"
  youtube = "tmeinershagen"
  # vimeo = "*"
  # vine = "*"
  # slideshare = "*"

  # SNS career oriented
  linkedin = "toddmeinershagen"
  # xing = "*"

  # SNS news
  # reddit = "*"
  # hackernews = "*"

  # Techie
  github = "toddmeinershagen"
  # gitlab = "*"
  # bitbucket = "*"
  stackoverflow = "573398/todd-meinershagen"
  # serverfault = "*"

  # Gaming
  # steam = "*"
  # mobygames = "*"

  # Music
  # lastfm = "*"
  # discogs = "*"

  # Other
  # keybase = "*"